version: '3.7'

services:
  mongo:
    image: mongo
    ports:
      - 8001:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: m-nny
      MONGO_INITDB_ROOT_PASSWORD: change-in-production
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8002:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: m-nny
      ME_CONFIG_MONGODB_ADMINPASSWORD: change-in-production
      ME_CONFIG_MONGODB_URL: mongodb://m-nny:change-in-production@mongo:27017/

volumes:
  mongo_data:
